GET http://localhost:3001/api/notes/672f40edde3fceacb12


###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Using rest client to send request",
    "important":false
}

###
DELETE http://localhost:3001/api/notes/672f40edde3fcea53c61cb12

###
PUT http://localhost:3001/api/notes/672f543aabbea52e94b0698b
Content-Type: application/json

{
    "content":"roh",
    "important":true
}
